# Generated by Django 4.1.7 on 2023-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_manualinput_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualinput',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='analysis_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='b_lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='bas',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_cd4_cd3_cd8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_ifny_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_ifny_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_il2_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_il2_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_tnfa_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='cd3_tnfa_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='circ_immu_comps',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='co_diagnosis',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='common_nk_cells',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='eos',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='fno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='genes1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='genes2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='genes3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='hct_test_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='hct_test_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='hgb',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='key',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='leu_wbc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='main_diagnosis',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='manwom',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='mon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='neu',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='nk_cells_cyto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='season',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='t_cyto_lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='t_help',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='t_lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manualinput',
            name='trom_plt',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='bas',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='bas_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='bas_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_cd4_cd3_cd8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_cd4_cd3_cd8_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_cd4_cd3_cd8_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_ifny_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_ifny_spon_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_ifny_spon_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_ifny_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_ifny_stim_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_ifny_stim_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_il2_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_il2_spon_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_il2_spon_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_il2_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_il2_stim_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_il2_stim_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_tnfa_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_tnfa_spon_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_tnfa_spon_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_tnfa_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_tnfa_stim_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='cd3_tnfa_stim_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='circ_immu_comps',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='circ_immu_comps_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='circ_immu_comps_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_b_lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_b_lymf_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_b_lymf_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_nk_cells',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_nk_cells_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_nk_cells_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_t_lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_t_lymf_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='common_t_lymf_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='eos',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='eos_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='eos_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hct_test_spon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hct_test_spon_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hct_test_spon_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hct_test_stim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hct_test_stim_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hct_test_stim_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hgb',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hgb_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='hgb_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='leu_wbc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='leu_wbc_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='leu_wbc_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='lymf_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='lymf_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='mon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='mon_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='mon_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='neu',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='neu_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='neu_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='nk_cells_cyto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='nk_cells_cyto_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='nk_cells_cyto_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='recomendations',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='season',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='t_cyto_lymf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='t_cyto_lymf_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='t_cyto_lymf_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='t_help',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='t_help_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='t_help_min',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='trom_plt',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='trom_plt_max',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='trom_plt_min',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
