# Generated by Django 4.1.4 on 2023-07-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_manualinput_age_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manualinput',
            table='analysis_manualinput',
        ),
    ]
