# Generated by Django 4.1.4 on 2023-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_manualinput_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualinput',
            name='num',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='manualinput',
            table=None,
        ),
    ]
